### ISSUE TITLE
bug in surface_profiling.py

### ISSUE THREAD

**Issue by gauzias** [brain-slam/slam#62] opened 2021-01-27 10:57 UTC
example_surface_profiling.py and example_profile_texture.py are broken due to a bug in surface_profiling.py:

profile_points = surfpf.surface_profiling_vert(
TypeError: surface_profiling_vert() takes 6 positional arguments but 7 were given

 profile_samples, profile_co_faces = surfpf.second_round_profiling_vert(
AttributeError: module 'slam.surface_profiling' has no attribute 'second_round_profiling_vert'

**Comment by alexpron** [comment] 2021-01-28 13:47
Hello @gauzias unfortunately I am unable to reproduce the bug you encountered. I ran the tests using latest master version of slam and found no issues. May be due to not up to date code ?

```bash
 pytest tests/test_surface_profiling.py 
====================================================================================================== test session starts ======================================================================================================
platform linux -- Python 3.6.12, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/alex/code/slam
collected 1 item                                                                                                                                                                                                                

tests/test_surface_profiling.py .                                                                                                                                                                                         [100%]

======================================================================================================= 1 passed in 0.50s =======================================================================================================
pytest tests/test_texture.py 
====================================================================================================== test session starts ======================================================================================================
platform linux -- Python 3.6.12, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /home/alex/code/slam
collected 1 item                                                                                                                                                                                                                

tests/test_texture.py .                                                                                                                                                                                                   [100%]

======================================================================================================= 1 passed in 0.41s 
=======================================================================================================
```

**Comment by gauzias** [comment] 2021-01-28 20:48
Mmmm yes you're right @alexpron, pytest runs correctly for me too, and I can run the example too.
I get the following error, but only when I try to build the doc.
So that is specific to the generation of the doc...

Extension error:
Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/mnt/data/work/python_sandBox/slam/examples/example_surface_profiling.py failed leaving traceback:
Traceback (most recent call last):
  File "/mnt/data/work/python_sandBox/slam/examples/example_surface_profiling.py", line 43, in <module>
    profile_points = surfpf.surface_profiling_vert(
TypeError: surface_profiling_vert() takes 6 positional arguments but 7 were given


/mnt/data/work/python_sandBox/slam/examples/example_profile_texture.py failed leaving traceback:
Traceback (most recent call last):
  File "/mnt/data/work/python_sandBox/slam/examples/example_profile_texture.py", line 47, in <module>
    profile_samples, profile_co_faces = surfpf.second_round_profiling_vert(
AttributeError: module 'slam.surface_profiling' has no attribute 'second_round_profiling_vert'

**Comment by alexpron** [comment] 2021-07-06 12:22
I think the issue was solved. I close it dont hesitate to reopen it if needed

**Closed by alexpron** 2021-07-06 12:22 UTC
